### PR TITLE
Add text mapper to UI Provider

### PR DESCRIPTION
**Pull request by LarryLuTW**
- Update development script
- Add i18n context in provider

---
This change is [Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)

### CODE REVIEW

**Comment by silgal** [comment]
I think we should move i18ncontext out of packages/ui/src/lib/Provider/index.tsx for SRP.

In my imagination, the init is:

```
<Provider t={() => {}>
  <PostCard />
</Provider>
```

In PostCard:
```
const PostCard = () => {
  const { t } = useTranslation();
};
```

What do you think?

**Comment by silgal** [comment]
*[`packages/ui/src/lib/Provider/index.tsx` line 81 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GX5131vIIb2n1tpEC:-N6GX5131vIIb2n1tpED:bnskvl2) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L81)):*
> ```XML
> Provider.defaultProps = {
>   translationFunc: (text: string) => text,
> };
> ```

We can remove this once we've migrated flareon to use <Provider t={...} />?

**Comment by silgal** [comment]
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6GXOW00rkOgWZJk1wP:b-1gdahg) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
> ```XML
> 
> export default function Provider({ children, translationFunc }: ProviderProps) {
>   const i18nValue = useMemo(() => ({ t: translationFunc }), [translationFunc]);
> ```

Why do we have to memo?

**Review by silgal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

**Review by LarryLuTW — COMMENTED** [review]
Do you mean we should put I18NContext in maybe like `packages/ui/src/lib/i18n`, so we can use it like this?

```ts
// In ui/src/lib/i18n/index.tsx
const I18NContext = React.createContext({});
export const useTranslation = () => useContext(I18NContext);
export const I18NProvider = I18NContext.Provider
```

```ts
// In ui/src/lib/Provider/index.tsx
import { I18NProvider } from '../i18n'
return (
    <NativeBaseProvider theme={theme}>
      <I18NProvider value={i18nValue}>{children}</I18NProvider>
    </NativeBaseProvider>
)
```

> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14#-:-N6GXv330VousWtsu-yC:bm08b02)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6GZmCiEqYEQxT1BFjz:b-qjwsxw) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Why do we have to memo?
</blockquote></details>

if we pass `{ t: translationFunc }` to `I18NContext.Provider`, react will think it's a different object and rerender the whole tree every time.

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 81 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GX5131vIIb2n1tpEC:-N6G_GW878Pe18JrfiiW:b-6hnjmx) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L81)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

We can remove this once we've migrated flareon to use <Provider t={...} />?
</blockquote></details>

Yes, also update `propTypes.translationFunc` from `PropTypes.func` to `PropTypes.func.isRequired`.

**Review by silgal — CHANGES_REQUESTED** [review]
right

> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14#-:-N6HAJbs8l4ubBJFqfTG:b-7jzv7t)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6HARSj-Y-4_QjTgQpy:bg5fqiw) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

if we pass `{ t: translationFunc }` to `I18NContext.Provider`, react will think it's a different object and rerender the whole tree every time.
</blockquote></details>

Can we not wrap it inside an object?

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6HVvuGDXsaT6YaY779:b-atha3c) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Can we not wrap it inside an object?
</blockquote></details>

It will still change in every render if it's wrapped inside an object, unless we can put this object outside of the render function.

```tsx
function Provider({ children, translationFunc }: ProviderProps) {
    const i18nValue = { t: translationFunc };
    return (
        <NativeBaseProvider theme={theme}>
            <I18NContext.Provider value={i18nValue}>{children}</I18NContext.Provider>
        </NativeBaseProvider>
    );
}
```

**Review by silgal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 60 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6L2rI74zS04et25KuU:-N6L2rI74zS04et25KuV:b-81besu) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L60)):*
> ```XML
> const propTypes = {
>   children: PropTypes.node.isRequired,
>   translationFunc: PropTypes.func,
> ```

Rename to t for consistency?
___
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6L26UHEnJLgzBKepHK:b653xvp) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

It will still change in every render if it's wrapped inside an object, unless we can put this object outside of the render function.

```tsx
function Provider({ children, translationFunc }: ProviderProps) {
    const i18nValue = { t: translationFunc };
    return (
        <NativeBaseProvider theme={theme}>
            <I18NContext.Provider value={i18nValue}>{children}</I18NContext.Provider>
        </NativeBaseProvider>
    );
}
```
</blockquote></details>

Thanks yes, it will still change in every render if it's wrapped inside an object.

But what if it's not wrapped inside an object?

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @silgal)

___
*[`packages/ui/src/lib/Provider/index.tsx` line 60 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6L2rI74zS04et25KuU:-N6LstoEAH8CkIe3jAb7:bq0ncok) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L60)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Rename to t for consistency?
</blockquote></details>

sounds good
___
*[`packages/ui/src/lib/Provider/index.tsx` line 69 at r1](https://reviewable.io/reviews/utofundevelop/ui/14#-N6GXOW00rkOgWZJk1wO:-N6Lt1w_Bs7lxctljkTO:ba6e9qq) ([raw file](https://github.com/utofundevelop/ui/blob/88455f5b602b8d568b82bb3899a7e4610ffc8542/packages/ui/src/lib/Provider/index.tsx#L69)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Thanks yes, it will still change in every render if it's wrapped inside an object.

But what if it's not wrapped inside an object?
</blockquote></details>

Oh, I misread your question yesterday XD. Do you mean we just pass `translationFunc` as `value`? I think it's good.

```tsx
<I18NContext.Provider value={translationFun}>{children}</I18NContext.Provider>
```

**Review by silgal — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: all files reviewed, 4 unresolved discussions (waiting on @LarryLuTW)

___
*[`packages/ui/src/lib/i18n/index.ts` line 5 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXff5AF1xHFap5nTL:-N6MXff5AF1xHFap5nTM:b-7mt9k0) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/i18n/index.ts#L5)):*
> ```XML
> const I18NContext = React.createContext({});
> 
> export const useTranslation = () => ({ t: useContext(I18NContext) });
> ```

memo?
___
*[`packages/ui/src/lib/Provider/index.tsx` line 61 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXDqxApgKjUIgUG2M:-N6MXDqxApgKjUIgUG2N:b-ig4j1o) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L61)):*
> ```XML
> const propTypes = {
>   children: PropTypes.node.isRequired,
>   t: PropTypes.func,
> ```

Since this is a pass through to the provider, should this prop type be from the i18n file?
___
*[`packages/ui/src/lib/Provider/index.tsx` line 70 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXLo58hMpXn3nc03j:-N6MXLo58hMpXn3nc03k:b-mby0fg) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L70)):*
> ```XML
>     <NativeBaseProvider theme={theme}>
>       {/* translation function t must exist because we have default props */}
>       <I18NProvider value={t!}>{children}</I18NProvider>
> ```

Interesting, perhaps we should type the provider correctly
___
*[`packages/ui/src/lib/Provider/index.tsx` line 78 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MW_QOCe8P1EN_KltO:-N6MW_QOCe8P1EN_KltP:b-7nphjy) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L78)):*
> ```XML
> 
> Provider.defaultProps = {
>   t: (text: string) => text,
> ```

Is this default part of the responsibility of the i18n file?

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: all files reviewed, 4 unresolved discussions (waiting on @silgal)

___
*[`packages/ui/src/lib/i18n/index.ts` line 5 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXff5AF1xHFap5nTL:-N6MefK37kEcljSD-kK_:b-896fix) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/i18n/index.ts#L5)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

memo?
</blockquote></details>

Done.
___
*[`packages/ui/src/lib/Provider/index.tsx` line 61 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXDqxApgKjUIgUG2M:-N6Q1eGB2850BO0WidAc:brkwc75) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L61)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Since this is a pass through to the provider, should this prop type be from the i18n file?
</blockquote></details>

make sense
___
*[`packages/ui/src/lib/Provider/index.tsx` line 70 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MXLo58hMpXn3nc03j:-N6Q3y833vpsPB5RuXcr:bhh7ruz) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L70)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Interesting, perhaps we should type the provider correctly
</blockquote></details>

Yes but that will need extra `eslint-disable`, so I think adding a line of comment is cleaner.
___
*[`packages/ui/src/lib/Provider/index.tsx` line 78 at r3](https://reviewable.io/reviews/utofundevelop/ui/14#-N6MW_QOCe8P1EN_KltO:-N6MgvfcCI8GqgC7_V5J:b-d5qjcs) ([raw file](https://github.com/utofundevelop/ui/blob/0a1028b8ce74280c99a8afcb06fbc4d5c7d511a6/packages/ui/src/lib/Provider/index.tsx#L78)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Is this default part of the responsibility of the i18n file?
</blockquote></details>

Agree, it should be part of i18n

**Review by silgal — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @LarryLuTW)

**Pull request merged**
