### PR TITLE
Publish @utofun/ui to npm

### PR DESCRIPTION
**Pull request by LarryLuTW**
https://app.asana.com/0/1166821020652779/1201524358817794/f

---
This change is [Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)

### CODE REVIEW

**Review by silgal — CHANGES_REQUESTED** [review]
See below

**Comment by silgal** [comment]
Let's use reviewable?

**Review by silgal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 2 unresolved discussions (waiting on @LarryLuTW)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNadf3XBLTEuzU5el):*
`Update` > `Add`?
___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JNrmM2dP9qRWg1oZg:bz3i1zj) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
> ```JSON
>   "files": [
>     "src/lib/*/index.tsx"
>   ]
> ```

I think MenuItem.tsx won't be packed.



_Code quote:_
```JSON
  "files": [
    "src/lib/*/index.tsx"
  ]
```

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JRASd3EVH9l3YhHvH:b-pdxyah) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

I think MenuItem.tsx won't be packed.
</blockquote></details>

Oh, right. How about we change it to the following to include all files in `src/lib` except stories.



_Code snippet:_
```JSON
  "files": [
    "src/lib/",
    "!src/lib/*/index.stories.tsx"
  ]
```

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 2 unresolved discussions (waiting on @silgal)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNadf3XBLTEuzU5el):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

`Update` > `Add`?
</blockquote></details>

LGTM.

**Review by silgal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JUdLY1VXN_A7JfwPW:bwrcfi0) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

Oh, right. how about we change it to the following to include all files in `src/lib` except stories.
</blockquote></details>

As long as `npm pack` doesn't show extra files, I'm fine.

**Review by silgal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 2 unresolved discussions (waiting on @LarryLuTW and @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JV50zBZ_vaV-_Ga8l:b-vwd3wb) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

As long as `npm pack` doesn't show extra files, I'm fine.
</blockquote></details>

Sorry, I mean `npm publish --dry-run`

**Review by silgal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 1 unresolved discussion (waiting on @LarryLuTW)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JVO3G5z4KN5BKmeYK:b62tqoy) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Sorry, I mean `npm publish --dry-run`
</blockquote></details>

But why not `*.stories.tsx`?

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 1 unresolved discussion (waiting on @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JVYZO5sE8BhwivreJ:bu8c8jh) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

But why not `*.stories.tsx`?
</blockquote></details>

Agree, `*.stories.tsx` is better.

**Comment by silgal** [comment]
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JWRLH31DWJ2o1xwP1:b-mli9ac) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

Agree, `*.stories.tsx` is better.
</blockquote></details>

where did you find the ! syntax? I can't find it anywhere

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 1 unresolved discussion (waiting on @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2J_1fkEc7tQaDhvRGP:b-bk0b3h) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

where did you find the ! syntax? I can't find it anywhere
</blockquote></details>

My bad, I thought files field support blacklist. How about we give up setting files in `package.json`, and create a `.npmignore` like this instead?



_Code snippet:_
```JSON
*

# include all the files in src/lib
!src/lib/**/*

# then exclude all the stories
*.stories.tsx
```

**Comment by silgal** [comment]
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JaRyc9U30BpJ66QZm:brofabi) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

My bad, I thought files field support blacklist. How about we give up setting files in `package.json`, and create a `.npmignore` like this instead?
</blockquote></details>

This won't work, you should also try yourself.

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 1 unresolved discussion (waiting on @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2Ja48C9Rtf1j3TorVX:b-uxq1py) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

This won't work, you should also try yourself.
</blockquote></details>

This does work, but to keep it simple, I think we can just rename `MenuItem.tsx` to `MenuItem/index.tsx` and update `files` to : ["src/lib/**/index.tsx"]`. What do you think?

**Comment by silgal** [comment]
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2Jbhun78UUn-20Tn2b:b-wzn9g0) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

This does work, but to keep it simple, I think we can just rename `MenuItem.tsx` to `MenuItem/index.tsx` and update `files` to : ["src/lib/**/index.tsx"]`. What do you think?
</blockquote></details>

Intersting, it didn't work when I tried the last time. I think the least surprising way is to take the npm ignore approach per [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: all files reviewed, 1 unresolved discussion (waiting on @silgal)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JeJp2DKFQBjiu5r-6:b-fb60iq) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Intersting, it didn't work when I tried the last time. I think the least surprising way is to take the npm ignore approach per [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)
</blockquote></details>

Sure. I guess you might forget to remove the `files` field in `package.json` in your last try. If the `files` is defined, npm will not look into `.npmignore`.

**Comment by silgal** [comment]
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2JiAO7BBwZiZ230isL:by3djno) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, LarryLuTW (Larry Lu) wrote…</i></summary><blockquote>

Sure. I guess you might forget to remove the `files` field in `package.json` in your last try. If the `files` is defined, npm will not look into `.npmignore`.
</blockquote></details>

Interesting. BTW, when both files and .npmignore exists, it uses .npmignore, it just that .npmignore can't override what files matches

**Review by silgal — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11#-:-N2JidIp8WkcoyhYrvTA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @LarryLuTW)

**Review by LarryLuTW — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/utofundevelop/ui/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @LarryLuTW)

___
*[`packages/ui/package.json` line 82 at r1](https://reviewable.io/reviews/utofundevelop/ui/11#-N2JNrmM2dP9qRWg1oZf:-N2Jj1UpAVV9BVkCjhAw:bbnfbx1) ([raw file](https://github.com/utofundevelop/ui/blob/9a6da59eb8018cbc9afe0a5bd71eec0ac76d07b0/packages/ui/package.json#L82)):*
<details><summary><i>Previously, silgal wrote…</i></summary><blockquote>

Interesting. BTW, when both files and .npmignore exists, it uses .npmignore, it just that .npmignore can't override what files matches
</blockquote></details>

Oh, right. Thanks for your correction.

**Pull request merged**
